# Project information
terra.description=A configurable world generator plugin for Paper, Purpur, Folia, and Spigot
terra.source=https://github.com/AsagiriBeta/Terra
terra.issues=https://github.com/AsagiriBeta/Terra/issues
terra.wiki=https://github.com/PolyhedralDev/Terra/wiki
terra.license=MIT
# Gradle options
org.gradle.jvmargs=-Xmx4096M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.warning.mode=all

